export const plans = [
  {
    name: 'Starter',
    description: 'Perfect for small schools',
    price: '24,999',
    period: 'month',
    trialDays: 14,
    features: [
      'Up to 500 students',
      'Basic student management',
      'Attendance tracking',
      'Simple fee management',
      'Email support',
      'Mobile app access',
      'Basic reports',
    ],
    highlighted: false,
  },
  {
    name: 'Professional',
    description: 'Best for growing schools',
    price: '74,999',
    period: 'month',
    trialDays: 14,
    features: [
      'Up to 5,000 students',
      'Advanced student management',
      'Attendance & performance tracking',
      'Complete payment processing',
      'Grade management system',
      'Priority email & chat support',
      'Advanced analytics & reports',
      'SMS notifications',
      'Parent mobile app',
      'API access',
    ],
    highlighted: true,
  },
  {
    name: 'Enterprise',
    description: 'For large institutions',
    price: 'Custom',
    period: 'contact us',
    trialDays: 14,
    features: [
      'Unlimited students',
      'Full feature suite',
      '24/7 phone support',
      'Dedicated account manager',
      'Custom integrations',
      'Advanced security',
      'Multi-campus support',
      'Custom reports',
      'Staff training included',
      'SLA guarantee',
    ],
    highlighted: false,
  },
];
